###########################  tomcat start ###########################
server:
  port: 8080
  servlet:
    context-path: /
  tomcat:
    max-threads: 1000
    min-spare-threads: 30
    uri-encoding: UTF-8
###########################  tomcat end  #########################



############################### WxLogin end ##################################
wechat:
    appid:
    appsecret:
    scope:
    callBack:
############################### WxLogin end ##################################